import psycopg2
from datetime import datetime

# Database connection parameters
db_params = {
    "dbname": "Stationszuil",
    "user": "postgres",
    "password": "797979",
    "host": "localhost",
    "port": "5432"
}

# Sample feedback data to insert
naam = "testnaam"
feedback = "testfeedback"
datum = str(datetime.now())

# SQL INSERT INTO statement excluding feedbackid (assuming feedbackid is auto-generated by the database)
insert_query = "INSERT INTO feedback (naam, feedback, datum) VALUES (%s, %s, %s);"
try:
    # Connect to the database
    conn = psycopg2.connect(**db_params)

    # Create a cursor object
    cursor = conn.cursor()

    # Execute the SQL query
    cursor.execute(insert_query, (naam, feedback, datum))

    # Commit the transaction
    conn.commit()

    print("Feedback inserted successfully.")

except psycopg2.Error as e:
    print("Error:", e)

finally:
    # Close the cursor and connection
    cursor.close()
    conn.close()
